### ISSUE TITLE
Replica / high availability 

### ISSUE THREAD

**Issue by nodesocket** [Twingate/helm-charts#17]
Is it possible to specify replicas and deploy multiple connector pods for high availability? It seems like each and every connector requires a unique name and tokens though.

**Comment by ekampf** [comment]
Hey @nodesocket 
Sorry for the late reply.  You can't use the `Deployment` replicas to scale connector beyond 1.
The reason is - each connector needs to have its own unique token pair (that you create via the admin console).
If you increase the replica count we'll have multiple connectors talking to Twingate using the same keys - basically identifying as one and overriding each other.

The way to achieve HA is to provision multiple such token pair and then use helm to create multiple deployments each with its unique tokens.
(and you can automate this process using our [API](https://docs.twingate.com/docs/api-overview) or [Terraform provider](https://registry.terraform.io/providers/Twingate/twingate/latest/docs) )

**Comment by nodesocket** [comment]
@ekampf ok thanks for the reply. That makes sense. I need multiple `helm installs` then. It's a little odd as typically you scale helm charts by using replicas. I wonder if allowing multiple tokena passed in as params into the chart is an option and future optimization?

**Comment by lllsJllsJ** [comment]
+1 hope we can have this feature

**Comment by ekampf** [comment]
@nodesocket @lllsJllsJ Just some more context on the issue here - sure we could do some work to allow connectors to provision themselves to you can use a Deployment and scale it up to have more Connectors.
The real problem is actually with scaling down - you have clients connected to a Connector and if you kill they'll have to reconnect to another connector and depending on the time of workload they're running - they might notice or not. 
For example, on an HTTP resource (browser making a lot of small requests) - the probably wont notice.
But, if they're on an SSH session or in the middle of transferring a huge file - they might.

So the reason we do not allow this at the moment is we dont want admin to use scaling up\down too frequent or even set up an autoscaler and unknowingly cause these issues to their users. 

We are thinking of various graceful shutdown strategies that will allow this in the future...

**Comment by rkrishn7** [comment]
Hello! We're also looking to manage multiple connector instances through a single helm chart. I get that currently each connector instance needs a unique token pair, but has there been consideration around allowing an array of connectors in the chart? For example:

```yaml
connectors:
  - logLevel: "error"
    network: example
    existingSecret: connector-secret-1
  - logLevel: "info"
    network: example
    existingSecret: connector-secret-2
```
Then a deployment would be created for each entry in `connectors`. I imagine there would need to be some extra info required to differentiate deployments (e.g. suffixes), but doable nonetheless.

**Comment by conclusionlogic** [comment]
A Kubernetes controller accessing Twingate's API seems like the best option to me.
You could then deploy the Connector as a DaemonSet in an autoscaling environment or scale the Deployment or StatefulSet as desired.
Assuming the "graceful shutdown" challenge is addressed, this K8s controller would manage token injections for new Connector Pods and handle cleanup for terminated ones.
It could also dynamically expose various resources (Ingress, Service, etc.) to specific Twingate Networks based on K8s annotations or labels found in the cluster.

**Comment by ErezWeiss** [comment]
We solved it like this:

```
apiVersion: v2
name: twingate
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
  - name: connector
    repository: https://twingate.github.io/helm-charts
    version: 0.1.19
    alias: kubernetes-1
  - name: connector
    repository: https://twingate.github.io/helm-charts
    version: 0.1.19
    alias: kubernetes-2
```

Maybe it's a good idea to add it to the documentation.
